# Generated by Django 4.2.5 on 2023-09-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
