# Generated by Django 4.2.5 on 2023-09-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="isReleased",
            field=models.BooleanField(default=True, verbose_name="Released"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Added"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(verbose_name="Presentation"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(verbose_name="Duration (mins)"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Movie Title"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(verbose_name="Release Year"),
        ),
    ]
